name: Examen de selection CS Games
run-name: Testing pipeline
on:
  push:
    branches:
      - main
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: 
          python-version: '3.14'
      - run: pip3 install -r requirements.txt