name: Épreuve de DevOps
run-name: Testing pipeline
on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  linting:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ci-cd/sample-django-datatables-master
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: 
          python-version: '3.13'
      - run: pip3 install -r requirements.txt
      - run: ruff --config dev.ruff.toml check
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ci-cd/sample-django-datatables-master
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: 
          python-version: '3.13'
      - run: pip3 install -r requirements.txt
      - run: coverage run manage.py test

  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ci-cd/sample-django-datatables-master
          file: ci-cd/sample-django-datatables-master/Dockerfile
          push: true
          tags: ghcr.io/mehdiben7/csgames:latest