name: Épreuve de DevOps
run-name: Testing pipeline
on:
  push:
    branches:
      - main
jobs:
  linting:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ci-cd/sample-django-datatables-master
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: 
          python-version: '3.13'
      - run: pip3 install -r requirements.txt